### ISSUE TITLE
Expected test score and dev score

### ISSUE THREAD

**Issue by Ramanpreetsingh** [ofirnachum/tree_rnn#2]
Hi,

I have been working with your code. The dev score I get after 30 epochs is around 0.40 and test score is 0.41

What is the expected dev and test score i.e. the scores you got on your system?

Thanks in anticipation.

Raman

**Comment by ofirnachum** [comment]
The last time I ran it, I got ~0.80 for dev/test score at 30+ epochs.

**Comment by Ramanpreetsingh** [comment]
I have followed the instructions given you and trained it on the same data set. Could you point a possible reason for a low dev score while I am running it?

**Comment by ofirnachum** [comment]
Are you using the default options?  e.g. FINE_GRAINED = False, HIDDEN_DIM = 100, etc.

**Comment by Ramanpreetsingh** [comment]
I have set FINE_GRAINED to True and HIDDEN_DIM = 100 and rest is default.

**Comment by ofirnachum** [comment]
Ah, ok - then the scores I mentioned are for the default options.  I don't recall what the scores were for FINE_GRANED = True, but as long as the dev/test scores generally go up during training, it seems reasonable.

**Comment by Ramanpreetsingh** [comment]
Expected scores for FINE_GRAINED = True should be higher as compared to that of FINE_GRAINED = False?

**Comment by ofirnachum** [comment]
No, FINE_GRAINED = True means that the model is trained to predict one of 5 labels (different levels of positive or negative sentiment.  FINE_GRAINED = False means that the model is only trained to predict 3 possible labels (positive, negative, or neutral).  

It is easier to pick the correct label in the more general case of only 3 labels.

**Comment by Ramanpreetsingh** [comment]
This cleared my doubt . Thanks a lot for your help.
